name = "most-salon"
compatibility_date = "2024-12-01"
main = "src/worker.ts"

[assets]
directory = "./out"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "most-salon-db"
database_id = "c4dc8d6f-372c-4e8b-a83b-0793e1a8ad22"

[vars]
GOOGLE_CALENDAR_ID = "419547e75f51a06bfb363b7dc790a1d437e81b9931ce2eb444c7f9c5d69d7381@group.calendar.google.com"
